[workspace]
members = [
    "rust",
    "rust/rtcm2json/rtcm",
    "rust/rtcm2json/rtcm_cli",
]
exclude = [
    "c/afl/afl-runner",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

