[workspace]
members = [
    "rust",
    "rust/rtcm",
]
exclude = [
    "c/afl/afl-runner",
    "c/third_party/libsbp",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
