use super::data_types::*;
use deku::{ctx::Endian, prelude::*};
use serde::Serialize;

/// GPS Satellite Ephemeris Data
#[derive(Debug, PartialEq, Eq, Clone, Copy, DekuRead, DekuWrite, Serialize)]
#[deku(endian = "endian", ctx = "endian: Endian")]
pub struct Msg1019 {
    pub satellite_id: U6,
    pub week_number: U10,
    pub sv_accuracy: U4,
    pub code_on_l2: U2,
    pub idot: I14,
    pub iode: U8,
    pub t_oc: U16,
    pub a_f2: I8,
    pub a_f1: I16,
    pub a_f0: I22,
    pub iodc: U10,
    pub c_rs: I16,
    pub delta_n: I16,
    pub m_0: I32,
    pub c_uc: I16,
    pub e: U32,
    pub c_us: I16,
    pub a_1_2: U32,
    pub t_oe: U16,
    pub c_ic: I16,
    pub omega_0: I32,
    pub c_is: I16,
    pub i_0: I32,
    pub c_rc: I16,
    pub omega: I32,
    pub omegadot: I24,
    pub t_gd: I8,
    pub sv_health: U6,
    pub l2_p_data_flag: Bit1,
    pub fit_interval: Bit1,
}

/// GLONASS Satellite Ephemeris Data
#[derive(Debug, PartialEq, Eq, Clone, Copy, DekuRead, DekuWrite, Serialize)]
#[deku(endian = "endian", ctx = "endian: Endian")]
pub struct Msg1020 {
    pub satellite_id: U6,
    pub satellite_freq_channel_nr: U5,
    pub almanac_health: Bit1,
    pub almanac_health_avail_indi: Bit1,
    pub p1: U2,
    pub tk: U12,
    pub msb_of_bn_word: Bit1,
    pub p2: Bit1,
    pub tb: U7,
    pub xn_tb_first: IS24,
    pub xn_tb: IS27,
    pub xn_tb_second: IS5,
    pub yn_tb_first: IS24,
    pub yn_tb: IS27,
    pub yn_tb_second: IS5,
    pub zn_tb_first: IS24,
    pub zn_tb: IS27,
    pub zn_tb_second: IS5,
    pub p3: Bit1,
    pub gamma_n_tb: IS11,
    pub m_p: U2,
    pub m_ln_third: Bit1,
    pub tau_n_tb: IS22,
    pub m_delta_tau_n: IS5,
    pub en: U5,
    pub m_p4: Bit1,
    pub m_ft: U4,
    pub m_nt: U11,
    pub m_m: U2,
    pub additional_data_avail: Bit1,
    pub na: U11,
    pub tau_c: IS32,
    pub m_n4: U5,
    pub tau_gps: IS22,
    pub m_ln_fifth: Bit1,
    pub reserved: U7,
}

/// BDS Satellite Ephemeris Data
#[derive(Debug, PartialEq, Eq, Clone, Copy, DekuRead, DekuWrite, Serialize)]
#[deku(endian = "endian", ctx = "endian: Endian")]
pub struct Msg1042 {
    pub satellite_id: U6,
    pub week_number: U13,
    pub sv_urai: U4,
    pub idot: I14,
    pub aode: U5,
    pub t_oc: U17,
    pub a_2: I11,
    pub a_1: I22,
    pub a_0: I24,
    pub aodc: U5,
    pub c_rs: I18,
    pub delta_n: I16,
    pub m_0: I32,
    pub c_uc: I18,
    pub e: U32,
    pub c_us: I18,
    pub a_1_2: U32,
    pub t_oe: U17,
    pub c_ic: I18,
    pub omega_0: I32,
    pub c_is: I18,
    pub i_0: I32,
    pub c_rc: I18,
    pub omega: I32,
    pub omegadot: I24,
    pub t_gd1: I10,
    pub t_gd2: I10,
    pub sv_health: Bit1,
}

/// Galileo F/NAV Satellite Ephemeris Data
#[derive(Debug, PartialEq, Eq, Clone, Copy, DekuRead, DekuWrite, Serialize)]
#[deku(endian = "endian", ctx = "endian: Endian")]
pub struct Msg1045 {
    pub satellite_id: U6,
    pub week_number: U12,
    pub iodnav: U10,
    pub sisa_index: U8,
    pub idot: I14,
    pub t_oc: U14,
    pub a_f2: I6,
    pub a_f1: I21,
    pub a_f0: I31,
    pub c_rs: I16,
    pub delta_n: I16,
    pub m_0: I32,
    pub c_uc: I16,
    pub e: U32,
    pub c_us: I16,
    pub a_1_2: U32,
    pub t_oe: U14,
    pub c_ic: I16,
    pub omega_0: I32,
    pub c_is: I16,
    pub i_0: I32,
    pub c_rc: I16,
    pub omega: I32,
    pub omegadot: I24,
    pub bgd_e5a_e1: I10,
    pub nav_signal_health_status: U2,
    pub nav_data_validity_status: Bit1,
    pub reserved: U7,
}

/// Galileo I/NAV Satellite Ephemeris Data
#[derive(Debug, PartialEq, Eq, Clone, Copy, DekuRead, DekuWrite, Serialize)]
#[deku(endian = "endian", ctx = "endian: Endian")]
pub struct Msg1046 {
    pub satellite_id: U6,
    pub week_number: U12,
    pub iodnav: U10,
    pub sisa_index: U8,
    pub idot: I14,
    pub t_oc: U14,
    pub a_f2: I6,
    pub a_f1: I21,
    pub a_f0: I31,
    pub c_rs: I16,
    pub delta_n: I16,
    pub m_0: I32,
    pub c_uc: I16,
    pub e: U32,
    pub c_us: I16,
    pub a_1_2: U32,
    pub t_oe: U14,
    pub c_ic: I16,
    pub omega_0: I32,
    pub c_is: I16,
    pub i_0: I32,
    pub c_rc: I16,
    pub omega: I32,
    pub omegadot: I24,
    pub bgd_e5a_e1: I10,
    pub bgd_e5b_e1: I10,
    pub e5b_signal_health_status: U2,
    pub e5b_data_validity_status: Bit1,
    pub e1_b_signal_health_status: U2,
    pub e1_b_data_validity_status: Bit1,
    pub reserved: U2,
}
