[package]
name = "rtcm32json"
version = "0.1.0"
authors = ["Swift Navigation <dev@swiftnav.com>"]
edition = "2021"

[[bin]]
name = "rtcm32json"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3" }
rtcm = { path = "../rtcm", features = ["json"] }
serde_json = "1"
if_chain = "1"

[build-dependencies]
vergen = { version = "7", default-features = false, features = ["git"] }

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
