name: Haskell
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "haskell/**"
      - .github/workflows/haskell.yaml
  pull_request:
    paths:
      - "haskell/**"
      - .github/workflows/haskell.yaml

jobs:
  haskell:
    name: Build Haskell
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Build Haskell
        shell: bash
        env:
          TESTENV: stack
        run: |
          bash ./ci-build.sh
